# Generated by Django 5.1.1 on 2024-10-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='email_mentor',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='name_mentor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email_student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name_student',
        ),
    ]
