# Generated by Django 5.1.1 on 2024-10-08 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('users', '0002_remove_mentor_email_mentor_remove_mentor_name_mentor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Chat',
        ),
    ]
